# drf-auth

* 장고 버전 무조건 3.* 버전이어야합니다. 4부터는 urls.py에서 url이 없어져서 실행시키면 오류납니다!
